/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.kotlin-application-conventions")
    kotlin("plugin.serialization") version "1.9.22"
}

dependencies {
    implementation("com.h2database","h2", "2.2.224")
    implementation("org.jetbrains.kotlinx","kotlinx-serialization-json","1.6.0")
    implementation("org.jetbrains.exposed", "exposed-core", "0.47.0")
    implementation("org.jetbrains.exposed", "exposed-dao", "0.47.0")
    implementation("org.jetbrains.exposed", "exposed-jdbc", "0.47.0")
    implementation("org.jetbrains.exposed", "exposed-java-time", "0.47.0")
    implementation("org.slf4j", "slf4j-api", "2.0.9")
    implementation("org.slf4j", "slf4j-simple", "2.0.9")
    implementation("org.apache.commons:commons-text")
    implementation(project(":common"))
    implementation(project(":serverini"))
    implementation(project(":visitorini"))
}

application {
    // Define the main class for the application.
//    mainClass = "site.aleksa.hse.kpo.restorini.utilini.UtiliniAppKt"
}
